/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("window1");
gchar *s = N_("On screen");
gchar *s = N_("Variable width");
gchar *s = N_("Fixed width");
gchar *s = N_("Select HTML fixed width font");
gchar *s = N_("AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz");
gchar *s = N_("Select HTML variable width font");
gchar *s = N_("AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz");
gchar *s = N_("For printing");
gchar *s = N_("Variable width");
gchar *s = N_("Fixed width");
gchar *s = N_("Select HTML fixed width font for printing");
gchar *s = N_("AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz");
gchar *s = N_("Select HTML variable width font for printing");
gchar *s = N_("AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz");
gchar *s = N_("Fonts");
gchar *s = N_("Keybord Shortcuts");
gchar *s = N_("Behavior");
gchar *s = N_("Animated images");
gchar *s = N_("Magic links (FIXME: better label)");
gchar *s = N_("Spell checking");
gchar *s = N_("Spell Checking");
gchar *s = N_("Color");
gchar *s = N_("Language");
gchar *s = N_("Pick a color");
gchar *s = N_("Miscellaneous");
